image: python:latest

variables:
  PIP_CACHE_DIR: "c:/users/mrodr/appdata/local/pip/cache"

cache:
  paths:
    - .cache/pip

before_script:
  - python --version ; pip --version

test:
  script:
    - pip install ruff tox
    - pip install --editable ".[test]"
    - tox -e py,ruff
    
deploy:
  stage: deploy
  script:
    - docker-compose up -d
    - echo "Deploy Concluído!"
  environment: production