services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - api_remindersapp_data:/bitnami/postgresql
    
  backend:
    build:
      context: .
      dockerfile: ./core/backend/Dockerfile
    volumes:
      - ./core/backend:/remindersapp/core/backend
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    env_file:
    - .env
    environment:
      - API_URL=${API_URL}
      - POSTGRES_HOST=postgres

  frontend:
    build:
      context: ./core/frontend
    volumes:
      - ./core/frontend/build:/remindersapp/frontend/build
    ports:
      - '3000:3000' 
    depends_on:
      - backend
    env_file:
    - .env
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL} 



volumes:
  api_remindersapp_data: {}
