
services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=matheusoliveira
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=polls
    volumes:
      - polls_pg_data:/bitnami/postgresql
    
  backend:
     build:
      context: ./
     volumes:
      - ./:/remindersapp/backend
     ports:
      - '8000:8000'

  frontend:
    build:
      context: ./core/frontend
    volumes:
      - ./core/frontend:/remindersapp/frontend
    ports:
      - '3000:3000' 

volumes:
  polls_pg_data:
  polls_redis_data:
