version: '3'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=matheusoliveira
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=polls
    volumes:
      - polls_pg_data:/bitnami/postgresql
    
  web:
    build: .
    volumes:
      - .:/alan
    ports:
      - '4000:4000'
      - '8000:8000'

volumes:
  polls_pg_data:
  polls_redis_data:
