# Generated by Django 5.0.7 on 2024-08-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='response',
            field=models.TextField(blank=True),
        ),
    ]
