# Generated by Django 5.1 on 2024-09-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_reminder_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='conversation_id',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='location',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='user',
        ),
        migrations.AddField(
            model_name='reminder',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
