# Generated by Django 5.1 on 2024-09-10 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_reminder_description_remove_reminder_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='Descrição',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='Evento',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='Local',
            new_name='location',
        ),
    ]
